import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Bookmark,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  Clock,
  Copy,
  Download,
  Eye,
  EyeOff,
  Filter,
  Flag,
  Globe,
  Heart,
  HelpCircle,
  Home,
  Info,
  Link,
  Loader2,
  Mail,
  MapPin,
  MoreVertical,
  Paperclip,
  Pencil,
  Phone,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Shield,
  Star,
  Trash2,
  Upload,
  User,
  X,
  AlertTriangle,
  DollarSign,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type { LucideIcon };

export const ICON_CATALOG: Record<string, LucideIcon> = {
  "Add": Plus,
  "Alert": AlertTriangle,
  "Arrow Down": ArrowDown,
  "Arrow Left": ArrowLeft,
  "Arrow Right": ArrowRight,
  "Arrow Up": ArrowUp,
  "Attachment": Paperclip,
  "Bell": Bell,
  "Bookmark": Bookmark,
  "Calendar": Calendar,
  "Check": Check,
  "Check Solid": CheckCircle,
  "Chevron Down": ChevronDown,
  "Chevron Left": ChevronLeft,
  "Chevron Right": ChevronRight,
  "Chevron Up": ChevronUp,
  "Chevrons Left": ChevronsLeft,
  "Chevrons Right": ChevronsRight,
  "Clock": Clock,
  "Close": X,
  "Copy": Copy,
  "Delete": Trash2,
  "Dollar": DollarSign,
  "Download": Download,
  "Edit": Pencil,
  "Email": Mail,
  "Eye": Eye,
  "Eye Off": EyeOff,
  "Filter": Filter,
  "Flag": Flag,
  "Globe": Globe,
  "Heart": Heart,
  "Help": HelpCircle,
  "Home": Home,
  "Info": Info,
  "Link": Link,
  "Map": MapPin,
  "More": MoreVertical,
  "Phone": Phone,
  "Refresh": RefreshCw,
  "Search": Search,
  "Settings": Settings,
  "Shield": Shield,
  "Spinner": Loader2,
  "Star": Star,
  "Upload": Upload,
  "User": User,
  "Zap": Zap,
};

/** Sorted icon entries for rendering */
export const ICON_ENTRIES = Object.entries(ICON_CATALOG).sort(([a], [b]) =>
  a.localeCompare(b),
);

/** Get a LucideIcon by display name */
export function getIcon(name: string): LucideIcon | undefined {
  return ICON_CATALOG[name];
}
